# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: thisMarioPerez
email: hello@thismarioperez.com
phone: '863.978.7139'
description: >- # this means to ignore newlines until "baseurl:"
  The portfolio of web projects for thisMarioPerez.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thismarioperez.com" # the base hostname & protocol for your site, e.g. http://example.com

# Theme Social Media Info
github_username:  thismarioperez
instagram_username: thismarioperez
twitter_username: thismarioperez

# Build settings
markdown: kramdown

# Kramdown settings
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-favicon
  - jemoji

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      modifiers: "js-offset"
      data_attrs: "data-offset-top"
      
# Collections
collections:
  pages:
    output: true
    permalink: /:path
  home:
    output: false

################################################################################
# Plugin Configurations
################################################################################
# jekyll-seo-tag plugin config
logo: /assets/img/logo-thismarioperez.png
twitter:
  username: thismarioperez
  card: summary
social:
  name: Mario Perez
  links:
  - https://twitter.com/thismarioperez
  - https://instagram.com/thismarioperez
  - https://github.com/thismarioperez

# jekyll-favicon config
favicon:
  source: favicon.svg
  path: /assets/img/favicon

################################################################################
# File Managing
################################################################################
# The following items will not be processed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - source
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.js
  - webpack.cleanup-stats-plugin.js

# Files to keep when rebuilding to destination.
keep_files:
  - assets/img/favicon
